import { StyleSheet } from "react-native";
import { COLORS, FONTS } from "../../core/config";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    paddingHorizontal: 22,
    paddingTop: 58,
    paddingBottom: 10,
  },
  title: {
    fontFamily: FONTS.bold,
    fontSize: 30,
    color: COLORS.text,
    marginBottom: 6,
  },
  subtitle: {
    fontFamily: FONTS.regular,
    fontSize: 15,
    color: COLORS.muted,
    lineHeight: 22,
  },
  list: {
    paddingHorizontal: 22,
    paddingBottom: 110,
  },
  searchBox: {
    height: 56,
    backgroundColor: COLORS.white,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    marginTop: 12,
    marginBottom: 12,
  },
  searchIcon: {
    fontSize: 18,
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 14,
    color: COLORS.text,
  },
  locationInput: {
    height: 52,
    backgroundColor: COLORS.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 16,
    fontFamily: FONTS.regular,
    fontSize: 14,
    color: COLORS.text,
    marginBottom: 12,
  },
  filterTitle: {
    fontFamily: FONTS.bold,
    fontSize: 15,
    color: COLORS.text,
    marginTop: 8,
    marginBottom: 8,
  },
  chipsRow: {
    paddingBottom: 8,
  },
  chip: {
    height: 38,
    paddingHorizontal: 16,
    borderRadius: 19,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  chipActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  chipText: {
    fontFamily: FONTS.bold,
    color: COLORS.muted,
    fontSize: 13,
  },
  chipTextActive: {
    color: COLORS.white,
  },
  dateRangeBox: {
    backgroundColor: COLORS.white,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 14,
    marginBottom: 12,
  },
  clearDateButton: {
    height: 42,
    borderRadius: 18,
    backgroundColor: COLORS.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  clearDateText: {
    fontFamily: FONTS.bold,
    color: COLORS.primary,
    fontSize: 13,
  },
  clearAllButton: {
    height: 44,
    borderRadius: 20,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  clearAllText: {
    fontFamily: FONTS.bold,
    color: COLORS.white,
    fontSize: 13,
  },
  resultsText: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: COLORS.text,
    marginTop: 10,
    marginBottom: 12,
  },
  eventCard: {
    flexDirection: "row",
    backgroundColor: COLORS.white,
    borderRadius: 24,
    padding: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  eventImage: {
    width: 92,
    height: 92,
    borderRadius: 18,
    marginRight: 14,
  },
  eventInfo: {
    flex: 1,
  },
  eventCategory: {
    fontFamily: FONTS.bold,
    color: COLORS.primary,
    fontSize: 10,
    marginBottom: 5,
  },
  eventTitle: {
    fontFamily: FONTS.bold,
    color: COLORS.text,
    fontSize: 15,
    marginBottom: 5,
  },
  eventMeta: {
    fontFamily: FONTS.regular,
    color: COLORS.muted,
    fontSize: 12,
    marginBottom: 5,
  },
  eventDescription: {
    fontFamily: FONTS.regular,
    color: COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  emptyBox: {
    backgroundColor: COLORS.white,
    borderRadius: 26,
    padding: 26,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  emptyTitle: {
    fontFamily: FONTS.bold,
    color: COLORS.text,
    fontSize: 18,
    marginBottom: 6,
  },
  emptyText: {
    fontFamily: FONTS.regular,
    color: COLORS.muted,
    textAlign: "center",
    fontSize: 14,
    lineHeight: 20,
  },
});

export default styles;